/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Our
 */
public class addDetails extends javax.swing.JFrame {

    /**
     * Creates new form addDetails
     */
    public addDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSubject1 = new javax.swing.ButtonGroup();
        Subject2 = new javax.swing.ButtonGroup();
        Subject3 = new javax.swing.ButtonGroup();
        Subject4 = new javax.swing.ButtonGroup();
        Subject5 = new javax.swing.ButtonGroup();
        Subject6 = new javax.swing.ButtonGroup();
        Subject7 = new javax.swing.ButtonGroup();
        Citizenship = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        edtLeanerName = new javax.swing.JTextField();
        edtLearnerSurname = new javax.swing.JTextField();
        edtLearnerGrade = new javax.swing.JTextField();
        edtLearnerDOB = new javax.swing.JTextField();
        edtParentName = new javax.swing.JTextField();
        edtParentSurname = new javax.swing.JTextField();
        edtContact = new javax.swing.JTextField();
        edtAddress = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        iLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbEnglish = new javax.swing.JRadioButton();
        rbAfr = new javax.swing.JRadioButton();
        rbXhosa = new javax.swing.JRadioButton();
        rbTswane = new javax.swing.JRadioButton();
        rbZulu = new javax.swing.JRadioButton();
        rbMath = new javax.swing.JRadioButton();
        rbMathLit = new javax.swing.JRadioButton();
        rbLO = new javax.swing.JRadioButton();
        rbArt1 = new javax.swing.JRadioButton();
        rbEco1 = new javax.swing.JRadioButton();
        rbDrama1 = new javax.swing.JRadioButton();
        rbPhysics2 = new javax.swing.JRadioButton();
        rbBio2 = new javax.swing.JRadioButton();
        rbGeo2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbPhysics3 = new javax.swing.JRadioButton();
        rbHistory3 = new javax.swing.JRadioButton();
        rbAcc3 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        lblCID = new javax.swing.JLabel();
        edtCID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmDetails"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        lblHeading.setFont(new java.awt.Font("Sitka Text", 1, 34)); // NOI18N
        lblHeading.setText("Enter Enrollment Information");

        edtLeanerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLeanerNameActionPerformed(evt);
            }
        });

        edtLearnerSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLearnerSurnameActionPerformed(evt);
            }
        });

        edtLearnerDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLearnerDOBActionPerformed(evt);
            }
        });

        edtParentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtParentNameActionPerformed(evt);
            }
        });

        edtParentSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtParentSurnameActionPerformed(evt);
            }
        });

        edtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtContactActionPerformed(evt);
            }
        });

        edtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAddressActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        iLabel1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        iLabel1.setText("Learner Name:");

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel2.setText("Learner Surname:");

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel3.setText("Enroll Learner into Grade:");

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel4.setText("Learner Age:");

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel5.setText("Parent Name:");

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel6.setText("Parent Surname:");

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel7.setText("Parent Contact:");

        jLabel8.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel8.setText("Parent Address:");

        btgSubject1.add(rbEnglish);
        rbEnglish.setText("English");
        rbEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnglishActionPerformed(evt);
            }
        });

        btgSubject1.add(rbAfr);
        rbAfr.setText("Afrikaans");

        btgSubject1.add(rbXhosa);
        rbXhosa.setText("Xhosa");

        Subject2.add(rbTswane);
        rbTswane.setText("Tswane");

        Subject2.add(rbZulu);
        rbZulu.setText("Zulu");

        Subject3.add(rbMath);
        rbMath.setText("Math");

        Subject3.add(rbMathLit);
        rbMathLit.setText("Math Lit");

        Subject4.add(rbLO);
        rbLO.setText("Life Orientation");

        Subject5.add(rbArt1);
        rbArt1.setText("Art");

        Subject5.add(rbEco1);
        rbEco1.setText("Economics");
        rbEco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEco1ActionPerformed(evt);
            }
        });

        Subject5.add(rbDrama1);
        rbDrama1.setText("Drama");
        rbDrama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDrama1ActionPerformed(evt);
            }
        });

        Subject6.add(rbPhysics2);
        rbPhysics2.setText("Physics");
        rbPhysics2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPhysics2ActionPerformed(evt);
            }
        });

        Subject6.add(rbBio2);
        rbBio2.setText("Biology");
        rbBio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBio2ActionPerformed(evt);
            }
        });

        Subject6.add(rbGeo2);
        rbGeo2.setText("Geography");
        rbGeo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeo2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Subject 1:");

        jLabel9.setText("Subject 2:");

        jLabel10.setText("Subject 3:");

        jLabel11.setText("Subject 4:");

        jLabel12.setText("Subject 5:");

        jLabel13.setText("Subject 6:");

        jLabel14.setText("Subject 7:");

        Subject7.add(rbPhysics3);
        rbPhysics3.setText("Physics");

        Subject7.add(rbHistory3);
        rbHistory3.setText("History");

        Subject7.add(rbAcc3);
        rbAcc3.setText("Accounting");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Please Select Subjects :");

        Citizenship.add(rbYes);
        rbYes.setText("Yes");
        rbYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYesActionPerformed(evt);
            }
        });

        Citizenship.add(rbNo);
        rbNo.setText("No");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel16.setText("Are you a South African Citizen?");

        lblCID.setText("jLabel17");

        edtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCIDActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Parent Details :");

        btnBack.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/back.PNG"))); // NOI18N
        btnBack.setText("Home");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Learner Details:");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(iLabel1))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtLeanerName, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(edtLearnerSurname))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtLearnerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edtLearnerGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(rbEnglish)
                                                            .addComponent(rbAfr))
                                                        .addGap(22, 22, 22)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(rbTswane)
                                                            .addComponent(jLabel9)
                                                            .addComponent(rbZulu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(26, 26, 26)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(rbMath)
                                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(39, 39, 39)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel11)
                                                                    .addComponent(rbLO)))
                                                            .addComponent(rbMathLit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(rbXhosa))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbDrama1)
                                                    .addComponent(rbEco1)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(rbArt1))
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(55, 55, 55)
                                                                .addComponent(jLabel13))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(57, 57, 57)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(rbBio2)
                                                                    .addComponent(rbPhysics2)
                                                                    .addComponent(rbGeo2)))))))
                                            .addComponent(jLabel15)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(edtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(edtAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(edtParentName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(75, 75, 75)
                                                        .addComponent(jLabel16))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(edtParentSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(108, 108, 108)
                                                        .addComponent(rbYes)
                                                        .addGap(48, 48, 48)
                                                        .addComponent(rbNo)))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbPhysics3)
                                                    .addComponent(jLabel14)
                                                    .addComponent(rbHistory3)
                                                    .addComponent(rbAcc3)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCID)
                                                    .addComponent(edtCID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(327, 327, 327)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 469, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(lblHeading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtLeanerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iLabel1)
                    .addComponent(jLabel4)
                    .addComponent(edtLearnerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtLearnerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edtLearnerGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEnglish)
                    .addComponent(rbMath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLO)
                    .addComponent(rbArt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPhysics2)
                    .addComponent(rbPhysics3)
                    .addComponent(rbTswane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAfr)
                    .addComponent(rbZulu)
                    .addComponent(rbMathLit)
                    .addComponent(rbEco1)
                    .addComponent(rbBio2)
                    .addComponent(rbHistory3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbXhosa)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbDrama1)
                        .addComponent(rbGeo2)
                        .addComponent(rbAcc3)))
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtParentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCID))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtParentSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(rbYes)
                            .addComponent(rbNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(edtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomePage frmHome = new HomePage();
        frmHome.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String Subject1 = null;
        String Subject2 = null;
        String Subject3 = null;
        String Subject4 = null;
        String Subject5 = null;
        String Subject6 = null;
        String Subject7 = null;
        boolean Citizen = false;

        if (rbEnglish.isSelected()) {
            Subject1 = "English";
        }
        if (rbXhosa.isSelected()) {
            Subject1 = "Xhosa";
        }
        if (rbAfr.isSelected()) {
            Subject1 = "Afrikaans";
        }
        if (rbTswane.isSelected()) {
            Subject2 = "Tswane";
        }
        if (rbXhosa.isSelected()) {
            Subject2 = "Xhosa";
        }
        if (rbMath.isSelected()) {
            Subject3 = "Math";
        }
        if (rbMathLit.isSelected()) {
            Subject3 = "Math Lit";
        }
        if (rbLO.isSelected()) {
            Subject4 = "Life Orientation";
        }
        if (rbArt1.isSelected()) {
            Subject5 = "Art";
        }
        if (rbEco1.isSelected()) {
            Subject5 = "Economics";
        }
        if (rbDrama1.isSelected()) {
            Subject5 = "Drama";
        }
        if (rbPhysics2.isSelected()) {

            Subject6 = "Physics";
        }
        if (rbBio2.isSelected()) {
            Subject6 = "Biology";
        }
        if (rbGeo2.isSelected()) {
            Subject6 = "Geography";
        }
        if (rbPhysics3.isSelected()) {
            Subject7 = "Physics";
        }
        if (rbHistory3.isSelected()) {
            Subject7 = "History";
        }
        if (rbAcc3.isSelected()) {
            Subject7 = "Accounting";
        }
        if (rbYes.isSelected()) {
            Citizen = true;
        }
        if (rbNo.isSelected()) {
            Citizen = false;
        }

        String sName = edtLeanerName.getText();

        String sSurname = edtLearnerSurname.getText();
        String sAge = edtLearnerDOB.getText();
        Integer sGrade = Integer.parseInt(edtLearnerGrade.getText());
        String pName = edtParentName.getText();
        String pSurname = edtParentSurname.getText();
        String pNumber = edtContact.getText();
        String Address = edtAddress.getText();
        String CID = edtCID.getText();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            String path = "SchoolDatabase.mdb";

            String ur = "jdbc:ucanaccess://" + path;

            Connection con = DriverManager.getConnection(ur);

            String query = "INSERT INTO tblLearner VALUES ('" + sName + "', '" + sSurname + "', '" + sGrade + "', '" + sAge + "',  '" + pNumber + "')";
            Statement Stmt = con.createStatement();
            int rs = Stmt.executeUpdate(query);
            Statement st = con.createStatement();
            String qry = "INSERT INTO tblParent VALUES ('" + pName + "', '" + pSurname + "', '" + sName + "', '" + pNumber + "',  '" + Address + "',  '" + Citizen + "',  '" + CID + "')";
            Statement St = con.createStatement();
            int r = St.executeUpdate(qry);
            Statement s = con.createStatement();
            String y = "INSERT INTO tblAccepted VALUES ('" + sName + "', '" + sSurname + "','" + sAge + "', '" + Subject1 + "', '" + Subject2 + "','" + Subject3 + "','" + Subject4 + "','" + Subject5 + "','" + Subject6 + "','" + Subject7 + "','" + pNumber + "')";
            Statement S = con.createStatement();
            int rq = S.executeUpdate(y);
            Statement A = con.createStatement();

            System.out.println("Record inserted successfully.");
            con.close();
        } catch (Exception ex) {
            System.out.println("error occured " + ex);
        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void edtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtContactActionPerformed

    private void edtParentSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtParentSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtParentSurnameActionPerformed

    private void edtLeanerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLeanerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLeanerNameActionPerformed

    private void edtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAddressActionPerformed

    private void rbDrama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDrama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDrama1ActionPerformed

    private void rbEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEnglishActionPerformed

    private void rbBio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBio2ActionPerformed
        if (rbBio2.isSelected()) {
            rbPhysics3.setVisible(true);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_rbBio2ActionPerformed

    private void rbPhysics2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPhysics2ActionPerformed

        if (rbPhysics2.isSelected()) {
            rbPhysics3.hide();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_rbPhysics2ActionPerformed

    private void rbGeo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeo2ActionPerformed
        if (rbGeo2.isSelected()) {
            rbPhysics3.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rbGeo2ActionPerformed

    private void rbYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYesActionPerformed
        if (rbYes.isSelected()) {
            lblCID.setVisible(true);
            lblCID.setText("Enter South African ID :");
            edtCID.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rbYesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblCID.setVisible(false);
        edtCID.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        if (rbNo.isSelected()) {
            lblCID.setVisible(true);
            lblCID.setText("Enter Passport ID :");
            edtCID.setVisible(true);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_rbNoActionPerformed

    private void edtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCIDActionPerformed

    private void edtParentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtParentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtParentNameActionPerformed

    private void edtLearnerSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLearnerSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLearnerSurnameActionPerformed

    private void edtLearnerDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLearnerDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLearnerDOBActionPerformed

    private void rbEco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEco1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Citizenship;
    private javax.swing.ButtonGroup Subject2;
    private javax.swing.ButtonGroup Subject3;
    private javax.swing.ButtonGroup Subject4;
    private javax.swing.ButtonGroup Subject5;
    private javax.swing.ButtonGroup Subject6;
    private javax.swing.ButtonGroup Subject7;
    private javax.swing.ButtonGroup btgSubject1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtCID;
    private javax.swing.JTextField edtContact;
    private javax.swing.JTextField edtLeanerName;
    private javax.swing.JTextField edtLearnerDOB;
    private javax.swing.JTextField edtLearnerGrade;
    private javax.swing.JTextField edtLearnerSurname;
    private javax.swing.JTextField edtParentName;
    private javax.swing.JTextField edtParentSurname;
    private javax.swing.JLabel iLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCID;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JRadioButton rbAcc3;
    private javax.swing.JRadioButton rbAfr;
    private javax.swing.JRadioButton rbArt1;
    private javax.swing.JRadioButton rbBio2;
    private javax.swing.JRadioButton rbDrama1;
    private javax.swing.JRadioButton rbEco1;
    private javax.swing.JRadioButton rbEnglish;
    private javax.swing.JRadioButton rbGeo2;
    private javax.swing.JRadioButton rbHistory3;
    private javax.swing.JRadioButton rbLO;
    private javax.swing.JRadioButton rbMath;
    private javax.swing.JRadioButton rbMathLit;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbPhysics2;
    private javax.swing.JRadioButton rbPhysics3;
    private javax.swing.JRadioButton rbTswane;
    private javax.swing.JRadioButton rbXhosa;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JRadioButton rbZulu;
    // End of variables declaration//GEN-END:variables
}
